tosca_definitions_version: cloudify_dsl_1_3

plugins:
  ansible:
    executor: central_deployment_agent
    source: https://raw.githubusercontent.com/riskfocus/cloudify-ansible-plugin/master/plugin.zip
